# Generated by Django 2.2.4 on 2019-08-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planetID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('planetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting_app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('planetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting_app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerOfRecruit', models.BooleanField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting_app.Test')),
                ('recruitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting_app.Recruit')),
            ],
        ),
    ]
