# Generated by Django 2.2.4 on 2019-08-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='planetID',
            new_name='planet',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='recruitID',
            new_name='recruit',
        ),
        migrations.RenameField(
            model_name='sith',
            old_name='planetID',
            new_name='planet',
        ),
    ]
