# Generated by Django 2.2.4 on 2019-08-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_app', '0002_auto_20190830_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
