# Generated by Django 2.2.4 on 2019-08-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_app', '0004_auto_20190830_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='isHandOfShadow',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruit',
            name='isTested',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruit',
            name='sith_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiting_app.Sith'),
        ),
    ]
