# Generated by Django 3.0.3 on 2020-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_app', '0006_auto_20190830_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название планеты'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='isHandOfShadow',
            field=models.BooleanField(default=False, verbose_name='Является ли Рукой Тени'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='isTested',
            field=models.BooleanField(default=False, verbose_name='Пройден ли тест'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='result',
            name='answerOfRecruit',
            field=models.BooleanField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='test',
            name='correctAnswer',
            field=models.BooleanField(verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
    ]
